superusers:
  - username: eliasbakken
    state: present
    authorized_keys: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEVoE61UreMtgITTsdSoX2UzBmeLJitKsXRhia7EmJP0
  - username: mastensg
    state: present
    authorized_keys: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICOayiImJKc7Qfmp2i33QNreBZ+zatorDVP3IUEPXlch mastensg@reed
  - username: trygvis
    state: present
    authorized_keys: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPX+sVfRvl0+KxsDlbIutyB/Es3exTwNfDVHwi9orwz3 trygvis@birgitte
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJAzB6JB/hZ87M6ozsd7lgKxgOacEOZZRxa4ucs11lqq trygvis@conflatorio
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL3UZyrbXX7WMHqcZCRspkoSIfB6egrbOxXPf1zyZkAw trygvis@arius-v4
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEkisPUAai4P3Scj1gWdV2TcDr54tb20BDy0NAkGOZnF trygvis@akili-v2
  - username: tingo
    state: present
    authorized_keys: ""
  - username: royk
    state: absent
    authorized_keys: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJlXRj/vYaL3v/ynF4Z1Sc5up9b1hCdfSZv4bLzwLWYv roy@karlsbakk.net
  - username: odinho
    state: present
    authorized_keys: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOXi2hd00LZWMvVNPFGESL2KgmeeuxpYGzjvQU1eESEB odin@h
  - username: haavares
    state: present
    authorized_keys: ""
  - username: margrav
    state: present
    authorized_keys: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDrbAcmOIRSERVam1SKtMZDkST98ImyYVhRaW10RNF2YSgnmVbD6Wqq5oaFpGh4+9FVg9QbEx4O5FnSxGjnmJeVfTC162sK/oWl1NSZ4lmVALCOa0OnsbJ+AHGERBcv/6KoGCJ2slSRUgMkZEl46D2SP1mLH2HFhvugQMXWXBd8qBD3GmJ3QocR9bnWiJYE1uD57jkUpT2IJC9mgHoRR6inq/09lN/VANftlKvasrwgKGZwIU3nIquXSeHD9jtAP5rXzalRp+VJ8LM2zHKiRjRZf4FFgniruTT/fdYSdnvLqmo/yd0Y/nPxhESm9JqRQpKe6fdTJUJFwQ7SRTgHnVxp margrav@Martins-MacBook-Air.local
  - username: omega
    state: present
    authorized_keys: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPzUlNNCZe0FJ+0vz1sM9hYMNHJSWFgY6gqyAP0kWm+y
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDYI6OTHiS015oqVINoQ3zEl2CF02UmdEVeO3dzeX1Kv
  - username: hildenae
    state: present
    authorized_keys: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIeO3y1ScnOFJHt0HsbDpfmpokTw1QZgjKg8EnwXR+8/ hildenae@ember
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPQyer7CgKVX0HscM1Z/jxJbOqczQ9id5g75SCnD6OUl hildenae@offle
