# DO NOT REMOVE USERS FROM THIS FILE.
users:
  eliasbakken:
    authorized_keys: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEVoE61UreMtgITTsdSoX2UzBmeLJitKsXRhia7EmJP0
  mastensg:
    authorized_keys: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINu7CM1afBuVkmNeMkSItLSBkgPiGbLH12ThN8ajZh1U mastensg@hui
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG5f5N7gkHczXgr5LeMdU7dTBrrOsvId6ug/3mH7NZwS mastensg@miller
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMrG2u1KzUoj9YUPaqF5RLjt4685PYMsH93MPykHVMB3 mastensg@munkres
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICOayiImJKc7Qfmp2i33QNreBZ+zatorDVP3IUEPXlch mastensg@reed
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH5wp6WRmSE/UBGPYLy1ylVHDa+wUo96UGUCopgaSH/n mastensg@taylor
  trygvis:
    authorized_keys: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPX+sVfRvl0+KxsDlbIutyB/Es3exTwNfDVHwi9orwz3 trygvis@birgitte
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJAzB6JB/hZ87M6ozsd7lgKxgOacEOZZRxa4ucs11lqq trygvis@conflatorio
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL3UZyrbXX7WMHqcZCRspkoSIfB6egrbOxXPf1zyZkAw trygvis@arius-v4
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEkisPUAai4P3Scj1gWdV2TcDr54tb20BDy0NAkGOZnF trygvis@akili-v2
  tingo:
    authorized_keys: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKKM/xmF+qTf6Wc9zXbMA9Mx3qrq6YXHuFKQVStTQS1W tingo@bitraf
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAq/8+H4A29KrV8SqvF6V7vU8r5f6sXStVroqLZmAeRx tingo@bitraf (bsbox)
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINL2e5n0kvZIJmZx6jIct4nzU5stsFu7QYhNcoSrliqA tingo@z30b
  royk:
    authorized_keys: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJlXRj/vYaL3v/ynF4Z1Sc5up9b1hCdfSZv4bLzwLWYv roy@karlsbakk.net
  odinho:
    authorized_keys: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOXi2hd00LZWMvVNPFGESL2KgmeeuxpYGzjvQU1eESEB odin@h
  haavares:
    authorized_keys: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCjyYhjUXvIOg7T2yHGchEt0h03unxPmATeDhE7Lh6BAGbtgdJCDqhZr3FQrT1CLPwaHtNkAbSFKrxe+n+xV4Bh6jzPxc4fVRSUGHz3VrMojtxey7BMo3YmYgj7riHgAFiVg787VtE2tDQwuHoCGdafeSJPZEpUMvfLe4oUG6KE9i2sQpkFCuVharc/grna67NmAIyVxQYqA3KdoUO/i7W3P8bEpDj6s6F6H63iX9quOLmHc1tbS7kAkaB7EVvhOAbsDbo8cpkAFbUOX9UJS4tJfOGMrkTJ6IhO7HyXM6LmoS3sA6EFSYFbdM7UjpVk7/RwJ7WjW2Sm/8MbtIgklo9t haavares@helga-908.local
  drerik:
    authorized_keys: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCYF0qnGfyEehvPK87vaXvZ9hnse31RKSQ9OMS3XREOdAD1Tjv0G/JMNNOiHBg0Li+ESkk+oCJVa21z5lVsq5AyiTBBeDnAFGWlwf4JdqCsC/TOyAdG075j7sesT4iCUwcmnhokGpKgNqHMrwuOdd313ywP2PFPM7s0H/L0bAzUIdLLo2EUMgyeoWeEouejIuQEohce2Zu6HdwMlqCKeeABfUjE4zZDCmuyRSqdE1BfXk71lFZqEaUz/tdPZ/7GrAasxU8Awvtq3zQMqT4NKOibSW1avDg41QOBaJy3H8n3b0rS70jqO9wGQ0t+Sjh4OE1k+rh20e1M+uaafFCqzp3d erik@i7
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDUK8CZG/iNXMgBDHrEZwdtP7BHF/8WFcs7BH3ZFgpsi4emqzclxdBOt/yZxUbBBPk1ExnYWQyricUKzv6Sbjqnx8ndZjRDNEBY298HfPe31O4Ap67XHAgIlzwGHSF+grQtgr1bXt43z8+ChBEzD8/zOWNK8PgyfeK/2Jpt2jHkNHaKuv17MyqraF1ti3nlU2MiSDmXEN6X9W8VwmoodxCTdQA1PzueQAlXodgV5L4g9zb7PClrRiuNQ8wjjwj2b1DmBwReNUBIrW1ROKP9jHWzkqZfrZzUTyJfCKAYY0j43ngNmWk+1nSJJzTIvhwkfhLmtWUsFVrAEAPjLyuEYmlP erikks@login.redpill-linpro.com
  mattis:
    authorized_keys: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDZT7rK9c74U6DFotWTRuSW3JyOS6uMRlEOKwelfe1k/hxfHbzfKf0AjcK/penNk/+SnNykrfnutxc9vMmZp6P7GHPAAFXMqWzgs7FXFClCq+lSgty8VMg7yWCErMw0prFPQi8v49rdX26FpFMbi7ltt+FtWsqKa9mvccJcFw6HCXD6yx7iRwLGIQJM1nJPkgb3m7fme22w2WqTag76cMDBC2HUoXHxBwHLWoAbs9249O6vDoR61k7po/cBWcGInxLh66B+VBDRoZoeo/H3LzQs18uHTWVzGj1Twa7jwo236qCfRy0CMwmnu4G7Y+1B2MgoAEimN/SkL0jPit1y5qY9 mattis@ultramattis
  talimere:
    authorized_keys: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDHZdOCygEURuxEypfeJyZJH95IpDkMeMuS215Etccljgl5q/qxtIiam/yKhZVWLl8ShgAJV57ak9TqIFBaTskTrxSsX9axMgtwcIwrnIo19R24KYgCliKDCJBtAl7Q886ZWYX8mLHWjVBFK1Bv9myQOF6nUecQGPwVeH6IhHSRTT9X2ATB5YyPaixqKpNdg+zYdyt2m8HKuIIfqfisqs6duLixuwBX0Tb98GGQTpXkM4SoYPKclMsdtaCF3w7+azsEPyKlqg3dzE0EaaIu5cX9FgUCs7IT901vAzT07K6JsHi7Ph2GZ4EvqJZlMtURMNv0MOYX9UJa5CFV7Lvo0OxhYXtmSZcGJWet68dAYZJl+4LCGNBTQwo6qviqF8OYUMsc6uI2hhmE6BgSVpdJSeMltGReDTqn8dXPKzET+mWNKMpFeYjBUOKdeF+HviM0Ibz0mNNiE2pS+487hNaHdgq0Dked1vXy+4Fd07gxi31Hay+LS2Nvjz1qVyc70qugxuFE2Oq1Zuf1jIWeLtWM+wM93dwlDL1sBsI4IQ3TDbloYhAiCUDxCo3gh8ejaTZ24MHFILi8b+vpYjJmYv5zSc40/SR4R4a+RMlqYQFp4CXSCJBsorg+MrwrLuyn+CzHnX67BnDJnu2GSjv25eRU7Qj6w/pYtBuTrcjKCxWKRP8oww== morkai16@student.westerdals.no
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC7vES08z1Mw9RtkM5SlsvGH6KuJA3N4n/9jt5O0T3FIIBxoRnbIu6RlaVdwbTWGGh8knSEJc9oMctJDNeiFHwdurPdzpRnViwK0y6tZH0BsN9/qaA8HnH6HtjT24zd24DSogihCHv8r1n5AiDXng6xLxCR7/vO9CuYYh/bogG8TGfkS6YLWltSlKb75b/eSuGEVle+AWXT/eWZ4zRzxGwUFrZMCZUiintC0RUvq6x79YFlMcoW9sEzM0EVZEPbk/MMz2MZGcXo97yNkHB70nIDA5G137dqH1GL/2qTYPwK5tWfgKeFdhGfduaq2ZOFvboaemaSgLVqaLCMZml9iG6s/4IobROeLudPyISRQPvx3ukA28RWdsQHje1f1vOePX+kBoEQ6vNF5rYdoziyIeBfdebye7sVlnwQsGFJ5wb9qjc46zmiRh0oEhATHw436AQdAksGjFruNEA0oQ+pKeNOlZqdO777dPaCGagib7RahY+rPQqb6LxUgtQ4IKyyrWt7w79TtKcdWr/K/I049ro2aUf2gHPTxVJ1QBkZ1th7Lt4iISkYfG6hPLPyFHxfLX/tKbSoyWj7GR0p3lEDa3jlVWEiNnN+f3jmurInZUzlfooKHNGNimXOrp9cVB9uHHVcJhPoHAyI768vAd+eWMh9twBTzpCMUMug+xL9UzjGkw== talimere@Scorpio-I
  jonnor:
    authorized_keys: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCRBQiYf6X7stPARBtfaPdVPkwG5ixmFiWRHhKzKIpbRX3DG2LcJgTWOoqysbs+lAxsMeHXROjkAcyEosxjWb+ng8HuPGP2SSNaECwVI7e/Ey6WEYgU+UrmV0su7f8m1gcmBz4esWfY02k+ojR3MxzrPdSHOnsBmofIgbcqLV/Fozf5FxpKHkneYfbFMcNvXAESnbg8UvMXcxMWbJTiRKntAayB1NJ5WfZADIrCmDhDN52I7AvTOqamdgAGt1pmpuuEacB/rCJqBZyDSpP9cOrnBfA4a6REErHlLK1OuDhBGN1kmhHMRtvmM4xbwgt8U++1zgokHVt4iXZi4jVsowj jon@jon-portable
  omega:
    authorized_keys: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPzUlNNCZe0FJ+0vz1sM9hYMNHJSWFgY6gqyAP0kWm+y omega@mbp
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDYI6OTHiS015oqVINoQ3zEl2CF02UmdEVeO3dzeX1Kv omega@pseudopolis
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIp09yo5XZE78/zdzP4fCtMdyuUHcs7AODAEYhR2YNow omega@mba
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEC1XSiVRFI/suElE8JrZIO2AkJeTOAZ9PpgSs4g8t5t omega@mbp-max
